services:
  db:
    image: postgres:15-alpine
    container_name: cafeteria_db_container
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
      - ./db/roles.sql:/docker-entrypoint-initdb.d/03_roles.sql
      - ./db/reports_vw.sql:/docker-entrypoint-initdb.d/04_reports_vw.sql
      - ./db/indexes.sql:/docker-entrypoint-initdb.d/05_indexes.sql
    networks:
      - cafeteria_net

  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DB_HOST: db
    depends_on:
      - db
    networks:
      - cafeteria_net

networks:
  cafeteria_net:
    driver: bridge